name: ci

on:
  push:
  pull_request:
  schedule: [cron: "40 1 * * *"]

jobs:

  # Run openraft unit test `openraft/` and integration test `tests/`.
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - toolchain: "stable"
          - toolchain: "nightly"


    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v4


      - name: Setup | Toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: "${{ matrix.toolchain }}"
          override: true

      - name: Install cargo-expand
        run: cargo install cargo-expand

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
        env:
          RUST_BACKTRACE: full


      - name: Test all features
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features
        env:
          RUST_BACKTRACE: full


  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: "nightly"
          components: rustfmt, clippy

      - name: Format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check


      - name: clippy
        shell: bash
        run: |
          cargo clippy --no-deps --workspace --all-targets                -- -D warnings
          cargo clippy --no-deps --workspace --all-targets --all-features -- -D warnings


      - name: Build-doc
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --all --no-deps
        env:
          RUSTDOCFLAGS: "-D warnings"


      - name: Audit dependencies
        shell: bash
        # if: "!contains(github.event.head_commit.message, 'skip audit')"
        run: cargo audit --db ./target/advisory-db
